# Generated by Django 4.2.2 on 2024-07-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(2, 'account'), (1, 'cash')], default=1, verbose_name='способ оплаты'),
        ),
    ]
