# Generated by Django 4.2.2 on 2024-07-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'cash'), (2, 'account')], default=1, verbose_name='способ оплаты'),
        ),
    ]
